apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: utopia-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/memory: "512Mi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/min-instances: "0"
        run.googleapis.com/max-instances: "10"
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/concurrency: "100"
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/utopia-backend
        ports:
        - containerPort: 8080
          name: http1
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "8080"
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api-key
              key: latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
          requests:
            memory: "256Mi"
            cpu: "0.5"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true 